//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAEP.WMS.Language.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YAEP.WMS.Language.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Can&apos;t add singal virtual product please add actual product 的當地語系化字串。
        /// </summary>
        public static string COMMON_CREATE_INVENTORY_CANNOT_ADD_SINGLE_VIRUALITEM {
            get {
                return ResourceManager.GetString("COMMON_CREATE_INVENTORY_CANNOT_ADD_SINGLE_VIRUALITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 data not found. 的當地語系化字串。
        /// </summary>
        public static string COMMON_DATA_NOT_FOUND {
            get {
                return ResourceManager.GetString("COMMON_DATA_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 some error occured. 的當地語系化字串。
        /// </summary>
        public static string COMMON_ERROR_OCCURED {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OCCURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 file format invaild must {0}. 的當地語系化字串。
        /// </summary>
        public static string COMMON_FILE_INVAILD {
            get {
                return ResourceManager.GetString("COMMON_FILE_INVAILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Generate label failure 的當地語系化字串。
        /// </summary>
        public static string COMMON_GENERATE_LABEL_FAILURE {
            get {
                return ResourceManager.GetString("COMMON_GENERATE_LABEL_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Can&apos;t not find UPC/EAN/SCC14/PUOM Label 的當地語系化字串。
        /// </summary>
        public static string COMMON_GENERATE_LABEL_NOT_FIND_LABEL {
            get {
                return ResourceManager.GetString("COMMON_GENERATE_LABEL_NOT_FIND_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 illegal guid. 的當地語系化字串。
        /// </summary>
        public static string COMMON_ILLEGAL_GUID {
            get {
                return ResourceManager.GetString("COMMON_ILLEGAL_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 illegal payload data 的當地語系化字串。
        /// </summary>
        public static string COMMON_ILLEGAL_PAYLOAD {
            get {
                return ResourceManager.GetString("COMMON_ILLEGAL_PAYLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Item# {0} Payload status must active  的當地語系化字串。
        /// </summary>
        public static string COMMON_ILLEGAL_PAYLOAD_STATUS {
            get {
                return ResourceManager.GetString("COMMON_ILLEGAL_PAYLOAD_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unable to process complex  payloads type 的當地語系化字串。
        /// </summary>
        public static string COMMON_ILLEGAL_PAYLOAD_TYPE {
            get {
                return ResourceManager.GetString("COMMON_ILLEGAL_PAYLOAD_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The slot is for Inbound only. 的當地語系化字串。
        /// </summary>
        public static string COMMON_ILLEGAL_SLOT_STATUS {
            get {
                return ResourceManager.GetString("COMMON_ILLEGAL_SLOT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 incorrect account. 的當地語系化字串。
        /// </summary>
        public static string COMMON_INCORRECT_ACCOUNT {
            get {
                return ResourceManager.GetString("COMMON_INCORRECT_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 incorrect format. 的當地語系化字串。
        /// </summary>
        public static string COMMON_INCORRECT_FORMAT {
            get {
                return ResourceManager.GetString("COMMON_INCORRECT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 incorrect parameters. 的當地語系化字串。
        /// </summary>
        public static string COMMON_INCORRECT_PARAMETERS {
            get {
                return ResourceManager.GetString("COMMON_INCORRECT_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 incorrect password. 的當地語系化字串。
        /// </summary>
        public static string COMMON_INCORRECT_PASSWORD {
            get {
                return ResourceManager.GetString("COMMON_INCORRECT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} status incorrect required:{1} current:{2} 的當地語系化字串。
        /// </summary>
        public static string COMMON_INCORRENT_STATUS {
            get {
                return ResourceManager.GetString("COMMON_INCORRENT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Item 的當地語系化字串。
        /// </summary>
        public static string COMMON_ITEM {
            get {
                return ResourceManager.GetString("COMMON_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find item info 的當地語系化字串。
        /// </summary>
        public static string COMMON_NOT_FIND_ITEM {
            get {
                return ResourceManager.GetString("COMMON_NOT_FIND_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} not find package info 的當地語系化字串。
        /// </summary>
        public static string COMMON_NOT_FIND_PACKAGE {
            get {
                return ResourceManager.GetString("COMMON_NOT_FIND_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not find workorder payload data. 的當地語系化字串。
        /// </summary>
        public static string COMMON_NOT_FIND_WORKORDER_PAYLOAD {
            get {
                return ResourceManager.GetString("COMMON_NOT_FIND_WORKORDER_PAYLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} not support  的當地語系化字串。
        /// </summary>
        public static string COMMON_NOT_SUPPORT {
            get {
                return ResourceManager.GetString("COMMON_NOT_SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Item {0} not match this package 的當地語系化字串。
        /// </summary>
        public static string COMMON_PKG_NOT_MATCH {
            get {
                return ResourceManager.GetString("COMMON_PKG_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The previous action is still in processing, please wait for it. 的當地語系化字串。
        /// </summary>
        public static string COMMON_REQUEST_ISPROCESSING {
            get {
                return ResourceManager.GetString("COMMON_REQUEST_ISPROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Some error occurred,please try again 的當地語系化字串。
        /// </summary>
        public static string COMMON_RETRY {
            get {
                return ResourceManager.GetString("COMMON_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sync onhand error please try again 的當地語系化字串。
        /// </summary>
        public static string COMMON_SYNC_ERROR {
            get {
                return ResourceManager.GetString("COMMON_SYNC_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} has multi-box, please adjust them together
        ///For item with multi-box, all boxes have to be the same qty and location 的當地語系化字串。
        /// </summary>
        public static string COMMON_VIRTUAL_ITEM_CHECK_INVALID {
            get {
                return ResourceManager.GetString("COMMON_VIRTUAL_ITEM_CHECK_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Can&apos;t combine actual item. 的當地語系化字串。
        /// </summary>
        public static string COMMON_VIRTUALITEM_COMBINE_FAILURE {
            get {
                return ResourceManager.GetString("COMMON_VIRTUALITEM_COMBINE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The warehouse does not have the related Slot, please change it. 的當地語系化字串。
        /// </summary>
        public static string COMMON_WAREHOSUE_SLOT_DIFFERENCE {
            get {
                return ResourceManager.GetString("COMMON_WAREHOSUE_SLOT_DIFFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to add customer address. 的當地語系化字串。
        /// </summary>
        public static string CUSTOMER_ADD_CUSTOMER_ADDRESS_FAIL {
            get {
                return ResourceManager.GetString("CUSTOMER_ADD_CUSTOMER_ADDRESS_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to add customer. 的當地語系化字串。
        /// </summary>
        public static string CUSTOMER_ADD_CUSTOMER_FAIL {
            get {
                return ResourceManager.GetString("CUSTOMER_ADD_CUSTOMER_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;Company&quot; can&apos;t be empty. 的當地語系化字串。
        /// </summary>
        public static string CUSTOMER_COMPANY_EMPTY {
            get {
                return ResourceManager.GetString("CUSTOMER_COMPANY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to delete customer. 的當地語系化字串。
        /// </summary>
        public static string CUSTOMER_DELETE_CUSTOMER_FAIL {
            get {
                return ResourceManager.GetString("CUSTOMER_DELETE_CUSTOMER_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;Customer ID&quot; can&apos;t be empty. 的當地語系化字串。
        /// </summary>
        public static string CUSTOMER_ID_EMPTY {
            get {
                return ResourceManager.GetString("CUSTOMER_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to update customer. 的當地語系化字串。
        /// </summary>
        public static string CUSTOMER_UPDATE_CUSTOMER_FAIL {
            get {
                return ResourceManager.GetString("CUSTOMER_UPDATE_CUSTOMER_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BOL 的當地語系化字串。
        /// </summary>
        public static string DATA_BOL_KEY {
            get {
                return ResourceManager.GetString("DATA_BOL_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Manifest 的當地語系化字串。
        /// </summary>
        public static string DATA_MANIFEST_KEY {
            get {
                return ResourceManager.GetString("DATA_MANIFEST_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ticket 的當地語系化字串。
        /// </summary>
        public static string DATA_TICKET_KEY {
            get {
                return ResourceManager.GetString("DATA_TICKET_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Vessel 的當地語系化字串。
        /// </summary>
        public static string DATA_VESSEL_KEY {
            get {
                return ResourceManager.GetString("DATA_VESSEL_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pallet#{0}  item:{1} can&apos;t allocated over volume  的當地語系化字串。
        /// </summary>
        public static string INBOUND_OVER_VOLUME {
            get {
                return ResourceManager.GetString("INBOUND_OVER_VOLUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find inbound landing zone 的當地語系化字串。
        /// </summary>
        public static string INBOUND_RECEIVING_NOT_FIND_LANDINGZONE {
            get {
                return ResourceManager.GetString("INBOUND_RECEIVING_NOT_FIND_LANDINGZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to add inventory quantity. 的當地語系化字串。
        /// </summary>
        public static string INVENTORY_ADD_QUANTITY_FAIL {
            get {
                return ResourceManager.GetString("INVENTORY_ADD_QUANTITY_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 have some item not belong to current group 的當地語系化字串。
        /// </summary>
        public static string INVENTORY_ITEM_NOT_BELONG_TO_GROUP {
            get {
                return ResourceManager.GetString("INVENTORY_ITEM_NOT_BELONG_TO_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Action Type incorrent 的當地語系化字串。
        /// </summary>
        public static string INVENTORY_MODIFY_INCORRENT_ACTION_TYPE {
            get {
                return ResourceManager.GetString("INVENTORY_MODIFY_INCORRENT_ACTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Payload#{0} modify qty insufficient 的當地語系化字串。
        /// </summary>
        public static string INVENTORY_MODIFY_INVENTORY_QTY_INSUFFICIENT {
            get {
                return ResourceManager.GetString("INVENTORY_MODIFY_INVENTORY_QTY_INSUFFICIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Modify qty must more than zero 的當地語系化字串。
        /// </summary>
        public static string INVENTORY_MODIFY_MOVE_CANNOT_ZERO {
            get {
                return ResourceManager.GetString("INVENTORY_MODIFY_MOVE_CANNOT_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Payload#{0} modify qty can&apos;t calculate to package 的當地語系化字串。
        /// </summary>
        public static string INVENTORY_MODIFY_QTY_UNABLE_CALCULATE {
            get {
                return ResourceManager.GetString("INVENTORY_MODIFY_QTY_UNABLE_CALCULATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find Slot 的當地語系化字串。
        /// </summary>
        public static string INVENTORY_NOT_FIND_SLOT {
            get {
                return ResourceManager.GetString("INVENTORY_NOT_FIND_SLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Modify Slot cannot empty 的當地語系化字串。
        /// </summary>
        public static string INVENTORY_SLOT_CANNOT_EMPTY {
            get {
                return ResourceManager.GetString("INVENTORY_SLOT_CANNOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Payload#{0} source Slot not same target slot 的當地語系化字串。
        /// </summary>
        public static string INVENTORY_SLOT_THE_SAME {
            get {
                return ResourceManager.GetString("INVENTORY_SLOT_THE_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 clear label failure. 的當地語系化字串。
        /// </summary>
        public static string LABEL_CLEAR_FAILURE {
            get {
                return ResourceManager.GetString("LABEL_CLEAR_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find labels. 的當地語系化字串。
        /// </summary>
        public static string LABEL_NOT_FIND_LABEL {
            get {
                return ResourceManager.GetString("LABEL_NOT_FIND_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find package tree. 的當地語系化字串。
        /// </summary>
        public static string LABEL_NOT_FIND_PKG_TREE {
            get {
                return ResourceManager.GetString("LABEL_NOT_FIND_PKG_TREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 must upload file. 的當地語系化字串。
        /// </summary>
        public static string LABEL_NOT_UPLOAD_FILE {
            get {
                return ResourceManager.GetString("LABEL_NOT_UPLOAD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not undefined belong to type. 的當地語系化字串。
        /// </summary>
        public static string LABEL_UNDEFINED_BELONGTO_TYPE {
            get {
                return ResourceManager.GetString("LABEL_UNDEFINED_BELONGTO_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 upload label failure please try again. 的當地語系化字串。
        /// </summary>
        public static string LABEL_UPLOAD_FAILURE {
            get {
                return ResourceManager.GetString("LABEL_UPLOAD_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Manifest Status must in Open. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_BOL_APPROVE_STATUS_ERROR {
            get {
                return ResourceManager.GetString("MANIFEST_BOL_APPROVE_STATUS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ticket has processed, can&apos;t reject  的當地語系化字串。
        /// </summary>
        public static string MANIFEST_BOL_REJECT_FAILURE_TICKET_WORKING {
            get {
                return ResourceManager.GetString("MANIFEST_BOL_REJECT_FAILURE_TICKET_WORKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BOL status must in Reivew. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_BOL_STATUS_MUST_IN_REVIEW {
            get {
                return ResourceManager.GetString("MANIFEST_BOL_STATUS_MUST_IN_REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BOL status must less than {0} status 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_BOL_STATUS_MUST_LESS_THAN {
            get {
                return ResourceManager.GetString("MANIFEST_BOL_STATUS_MUST_LESS_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Manifest Status must in Open stage. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_BOL_SUBMIT_STATUS_ERROR {
            get {
                return ResourceManager.GetString("MANIFEST_BOL_SUBMIT_STATUS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Following Item not assigned complete: 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_BOL_UNCOMPLETE_ASSIGNED {
            get {
                return ResourceManager.GetString("MANIFEST_BOL_UNCOMPLETE_ASSIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} cannot empty. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_CANNOT_EMPTY {
            get {
                return ResourceManager.GetString("MANIFEST_CANNOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WarehouseUID,ItemUID,PackageUID parameters not null 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_CHECKONHAND_LOST_PARAMETERS {
            get {
                return ResourceManager.GetString("MANIFEST_CHECKONHAND_LOST_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not receive parameters 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_COMMON_PARAMETERS_NULL {
            get {
                return ResourceManager.GetString("MANIFEST_COMMON_PARAMETERS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not find any request parameters. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_COMMON_REQUEST_NULL {
            get {
                return ResourceManager.GetString("MANIFEST_COMMON_REQUEST_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unique ID is null. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_COMMON_UNIQUE_NULL {
            get {
                return ResourceManager.GetString("MANIFEST_COMMON_UNIQUE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 It&apos;s not allowed to delete Manifest when the status is in Complete 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_DELETE_FAILURE_NOT_IN_STATUS {
            get {
                return ResourceManager.GetString("MANIFEST_DELETE_FAILURE_NOT_IN_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This warhouse not support future allocated 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_FUTURE_ALLOCATED_NOT_SUPPORT {
            get {
                return ResourceManager.GetString("MANIFEST_FUTURE_ALLOCATED_NOT_SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not find manifest or BOL. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_GENERATE_TICKET_ERROR {
            get {
                return ResourceManager.GetString("MANIFEST_GENERATE_TICKET_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unhandled exception has occurred : Fail to create items. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_INBOUND_ADD_ITEM_ERROR {
            get {
                return ResourceManager.GetString("MANIFEST_INBOUND_ADD_ITEM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 VesselManifest Name {0} allocated qty must less vessel manifest qty. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_INBOUND_ALLOCATED_QTY_OVER {
            get {
                return ResourceManager.GetString("MANIFEST_INBOUND_ALLOCATED_QTY_OVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 insufficient onhand. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_INSUFFICIENTONHAND {
            get {
                return ResourceManager.GetString("MANIFEST_INSUFFICIENTONHAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 must have items. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_MUST_HAVE_ITEM {
            get {
                return ResourceManager.GetString("MANIFEST_MUST_HAVE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 must have packageUID 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_MUST_HAVE_PACKAGE {
            get {
                return ResourceManager.GetString("MANIFEST_MUST_HAVE_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find BOL info. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_NOT_FIND_BOL_DATA {
            get {
                return ResourceManager.GetString("MANIFEST_NOT_FIND_BOL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not find data. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_NOT_FIND_DATA {
            get {
                return ResourceManager.GetString("MANIFEST_NOT_FIND_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find any item info. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_NOT_FIND_ITEM_INFO {
            get {
                return ResourceManager.GetString("MANIFEST_NOT_FIND_ITEM_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find manifest info. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_NOT_FIND_MANIFESTINFO_DATA {
            get {
                return ResourceManager.GetString("MANIFEST_NOT_FIND_MANIFESTINFO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find ticket info. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_NOT_FIND_TICKETINFO {
            get {
                return ResourceManager.GetString("MANIFEST_NOT_FIND_TICKETINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find vessel data. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_NOT_FIND_VESSEL_DATA {
            get {
                return ResourceManager.GetString("MANIFEST_NOT_FIND_VESSEL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 operate failure,please try again 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_OPERTAE_FAILURE {
            get {
                return ResourceManager.GetString("MANIFEST_OPERTAE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Allocated Failure 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_ORDER_ALLOCATED_FAILURE {
            get {
                return ResourceManager.GetString("MANIFEST_ORDER_ALLOCATED_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find customer uid 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_ORDER_ALLOCATED_NOT_FIND_CUSTOMERUID {
            get {
                return ResourceManager.GetString("MANIFEST_ORDER_ALLOCATED_NOT_FIND_CUSTOMERUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BulkPick is processing can&apos;t deallcated 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_ORDER_BULKPICK_PROCESSING {
            get {
                return ResourceManager.GetString("MANIFEST_ORDER_BULKPICK_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 cannot roll back ticket payload had been used 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_ORDER_INBOUND_ROLLBACKTICKET_USED {
            get {
                return ResourceManager.GetString("MANIFEST_ORDER_INBOUND_ROLLBACKTICKET_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to import. following item# duplicate {0} 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_ORDER_ITEM_DUPLICATE {
            get {
                return ResourceManager.GetString("MANIFEST_ORDER_ITEM_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to import. following item# is not in wms system {0} 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_ORDER_ITEM_NOT_FIND {
            get {
                return ResourceManager.GetString("MANIFEST_ORDER_ITEM_NOT_FIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The &quot;Stock UOM&quot;  and &quot;Inventory UOM&quot; for {0} are different from the smallest package setting in P item. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_ORDER_ITEM_NOT_MATCH_MIN_PACKAGE {
            get {
                return ResourceManager.GetString("MANIFEST_ORDER_ITEM_NOT_MATCH_MIN_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 There is no Crate/Pallet for {0}. Please set up Crate/Pallet in P item Packaging Setting 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_ORDER_ITEM_NOT_MATCH_PACKAGE {
            get {
                return ResourceManager.GetString("MANIFEST_ORDER_ITEM_NOT_MATCH_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to import. following item# not have package data {0} 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_ORDER_ITEM_NOT_PACKAGE {
            get {
                return ResourceManager.GetString("MANIFEST_ORDER_ITEM_NOT_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Future Allocated only for item of stock condition 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_ORDER_NOT_STOCK_REQUEST {
            get {
                return ResourceManager.GetString("MANIFEST_ORDER_NOT_STOCK_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 this order has already import 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_ORDER_RECEIVING_EXISTITEM {
            get {
                return ResourceManager.GetString("MANIFEST_ORDER_RECEIVING_EXISTITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 VesselManifest Name {0} allocated qty must less vessel manifest qty. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_OUTBOUND_ALLOCATED_QTY_OVER {
            get {
                return ResourceManager.GetString("MANIFEST_OUTBOUND_ALLOCATED_QTY_OVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order has complete. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_PICK_ALL_ALREADY_COMPLETE {
            get {
                return ResourceManager.GetString("MANIFEST_PICK_ALL_ALREADY_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 has future allocated data ,can&apos;t pick all 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_PICK_ALL_HAS_FUTURE_ALLOCATED {
            get {
                return ResourceManager.GetString("MANIFEST_PICK_ALL_HAS_FUTURE_ALLOCATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} Quantity must more than zero. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_QTY_MORE_THAN_ZERO {
            get {
                return ResourceManager.GetString("MANIFEST_QTY_MORE_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Following Vessel# has assgined please remove them {0} 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_REJECT_FAILURE_HAS_ASSIGNED_ITEM {
            get {
                return ResourceManager.GetString("MANIFEST_REJECT_FAILURE_HAS_ASSIGNED_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find request data. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_SAVEOUTBOUNDASSIGNEDITEM_LOST_PARAMETERS {
            get {
                return ResourceManager.GetString("MANIFEST_SAVEOUTBOUNDASSIGNEDITEM_LOST_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Manifest status incorrent must before {0} 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_STATUS_FAILURE {
            get {
                return ResourceManager.GetString("MANIFEST_STATUS_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 this data nothing to do. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_STATUS_NOACTION {
            get {
                return ResourceManager.GetString("MANIFEST_STATUS_NOACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Generate ticket lost warehouse UID 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_TICKET_GENERATE_MISS_WAREHOUSE {
            get {
                return ResourceManager.GetString("MANIFEST_TICKET_GENERATE_MISS_WAREHOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 have assigned item must remove first 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_VESSEL_DELETE_EXIST_ASSIGNED_WPAYLOAD {
            get {
                return ResourceManager.GetString("MANIFEST_VESSEL_DELETE_EXIST_ASSIGNED_WPAYLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find belong to packageUID package info 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_VESSEL_NOT_FIND_BELONGTO_PKG {
            get {
                return ResourceManager.GetString("MANIFEST_VESSEL_NOT_FIND_BELONGTO_PKG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Vessel status failure , must before {0} 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_VESSEL_STATUS_FAILURE {
            get {
                return ResourceManager.GetString("MANIFEST_VESSEL_STATUS_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Following items are insufficient qty {0} 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_AUTO_ASSIGN_INSUFFICIENT_QTY {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_AUTO_ASSIGN_INSUFFICIENT_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 There are no items allowed to operate. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_AUTO_ASSIGN_NO_ALLOWED_ITEM {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_AUTO_ASSIGN_NO_ALLOWED_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not find original payload info. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_DEALLOCATED_NOT_FIND_PAYLOAD {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_DEALLOCATED_NOT_FIND_PAYLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Workorder status failure ,must before {0} status 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_FAILURE_STATUS {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_FAILURE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 merge from must have data 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_MERAGE_POD_ERROR_FROM {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_MERAGE_POD_ERROR_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 merge to must have data 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_MERAGE_POD_ERROR_TO {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_MERAGE_POD_ERROR_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Must have item data. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_MUST_HAVE_ITEM {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_MUST_HAVE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Must have POD UID. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_MUST_HAVE_POD {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_MUST_HAVE_POD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 There are no slots allowed to operate. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_NO_ALLOWED_SLOT {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_NO_ALLOWED_SLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unable to load the unit of measure data for the pallet 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_NO_PALLET_UOM {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_NO_PALLET_UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to load the package data. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_NO_REF_PACKAGES {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_NO_REF_PACKAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Have some payload not assigned pod 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_NOT_ASSINGED_POD {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_NOT_ASSINGED_POD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find allocated payload info data. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_NOT_FIND_ALLOCATD_PAYLOAD {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_NOT_FIND_ALLOCATD_PAYLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find payload info data 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_NOT_FIND_PAYLOAD {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_NOT_FIND_PAYLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find vessel data. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_NOT_FIND_VESSEL {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_NOT_FIND_VESSEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not find vessel manifest data. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_NOT_FIND_VESSELMANIFST {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_NOT_FIND_VESSELMANIFST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not find workorder data. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_NOT_FIND_WORKORDER {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_NOT_FIND_WORKORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find workorderpayload data 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_NOT_FIND_WORKORDER_PAYLOAD {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_NOT_FIND_WORKORDER_PAYLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find workorderpod data 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_NOT_FIND_WORKORDER_POD {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_NOT_FIND_WORKORDER_POD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 no data to generate ticket. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_NOT_GENERATE_TICKET {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_NOT_GENERATE_TICKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} Payload TTL:{1} Allocated:{2} insufficient qty. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_OUTBOUND_INSUFFICIENTQTY {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_OUTBOUND_INSUFFICIENTQTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 have some tickets must void them. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_REMOVEPOD_ERROR {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_REMOVEPOD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 generate pod label failure. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_SET_POD_LABEL_ERROR {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_SET_POD_LABEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 must have WorkOrder Pod UID or WorkORder Payload UID 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_SETLANDINGSLOT_LOST_PARAMETER {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_SETLANDINGSLOT_LOST_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} must 1,2 or 3. 的當地語系化字串。
        /// </summary>
        public static string MANIFEST_WORKORDER_STOREAGE_METHOD_ERROR {
            get {
                return ResourceManager.GetString("MANIFEST_WORKORDER_STOREAGE_METHOD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 illegal status value 的當地語系化字串。
        /// </summary>
        public static string ORDER_ILLEGAL_STATUS {
            get {
                return ResourceManager.GetString("ORDER_ILLEGAL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Manifest type incorrect must outbound 的當地語系化字串。
        /// </summary>
        public static string ORDER_MANIFEST_TYPE_INCORRECT {
            get {
                return ResourceManager.GetString("ORDER_MANIFEST_TYPE_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to add item. 的當地語系化字串。
        /// </summary>
        public static string PRODUCT_ADD_ITEM_FAIL {
            get {
                return ResourceManager.GetString("PRODUCT_ADD_ITEM_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to add package. 的當地語系化字串。
        /// </summary>
        public static string PRODUCT_ADD_PACKAGE_FAIL {
            get {
                return ResourceManager.GetString("PRODUCT_ADD_PACKAGE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to add package version. 的當地語系化字串。
        /// </summary>
        public static string PRODUCT_ADD_PACKAGE_VERSION_FAIL {
            get {
                return ResourceManager.GetString("PRODUCT_ADD_PACKAGE_VERSION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to copy package version. 的當地語系化字串。
        /// </summary>
        public static string PRODUCT_CLONE_PACKAGE_VERSION_FAIL {
            get {
                return ResourceManager.GetString("PRODUCT_CLONE_PACKAGE_VERSION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to delete item. 的當地語系化字串。
        /// </summary>
        public static string PRODUCT_DELETE_ITEM_FAIL {
            get {
                return ResourceManager.GetString("PRODUCT_DELETE_ITEM_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to delete package. 的當地語系化字串。
        /// </summary>
        public static string PRODUCT_DELETE_PACKAGE_FAIL {
            get {
                return ResourceManager.GetString("PRODUCT_DELETE_PACKAGE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to delete package version. 的當地語系化字串。
        /// </summary>
        public static string PRODUCT_DELETE_PACKAGE_VERSION_FAIL {
            get {
                return ResourceManager.GetString("PRODUCT_DELETE_PACKAGE_VERSION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The &quot;Gross Weight&quot; must bigger than zero. 的當地語系化字串。
        /// </summary>
        public static string PRODUCT_GW_BIGGER_THAN_ZERO {
            get {
                return ResourceManager.GetString("PRODUCT_GW_BIGGER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;Item#&quot; can&apos;t be empty. 的當地語系化字串。
        /// </summary>
        public static string PRODUCT_ITEM_ID_EMPTY {
            get {
                return ResourceManager.GetString("PRODUCT_ITEM_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;Item Name&quot; can&apos;t be empty. 的當地語系化字串。
        /// </summary>
        public static string PRODUCT_ITEM_NAME_EMPTY {
            get {
                return ResourceManager.GetString("PRODUCT_ITEM_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The package does not exist. 的當地語系化字串。
        /// </summary>
        public static string PRODUCT_PACKAGE_NOT_EXIST {
            get {
                return ResourceManager.GetString("PRODUCT_PACKAGE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The &quot;Quantity&quot; must bigger than zero. 的當地語系化字串。
        /// </summary>
        public static string PRODUCT_QUANTITY_BIGGER_THAN_ZERO {
            get {
                return ResourceManager.GetString("PRODUCT_QUANTITY_BIGGER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The &quot;Receive Quantity&quot; must bigger than zero. 的當地語系化字串。
        /// </summary>
        public static string PRODUCT_RECEIVE_QTY_BIGGER_THAN_ZERO {
            get {
                return ResourceManager.GetString("PRODUCT_RECEIVE_QTY_BIGGER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The &quot;Length, Width, Height&quot; must bigger than zero. 的當地語系化字串。
        /// </summary>
        public static string PRODUCT_SIZE_BIGGER_THAN_ZERO {
            get {
                return ResourceManager.GetString("PRODUCT_SIZE_BIGGER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to update product category. 的當地語系化字串。
        /// </summary>
        public static string PRODUCT_UPDATE_ITEM_CATEGORY_FAIL {
            get {
                return ResourceManager.GetString("PRODUCT_UPDATE_ITEM_CATEGORY_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to update item. 的當地語系化字串。
        /// </summary>
        public static string PRODUCT_UPDATE_ITEM_FAIL {
            get {
                return ResourceManager.GetString("PRODUCT_UPDATE_ITEM_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to update package. 的當地語系化字串。
        /// </summary>
        public static string PRODUCT_UPDATE_PACKAGE_FAIL {
            get {
                return ResourceManager.GetString("PRODUCT_UPDATE_PACKAGE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ActQty must equal EstQty. 的當地語系化字串。
        /// </summary>
        public static string TICKET_ACTQTY_MUST_EQUAL_ESTQTY {
            get {
                return ResourceManager.GetString("TICKET_ACTQTY_MUST_EQUAL_ESTQTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add workder failure please try again. 的當地語系化字串。
        /// </summary>
        public static string TICKET_ADD_WORKER_FAILURE {
            get {
                return ResourceManager.GetString("TICKET_ADD_WORKER_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 following barcode had scanned {0} 的當地語系化字串。
        /// </summary>
        public static string TICKET_BARCODE_HAD_SCANED {
            get {
                return ResourceManager.GetString("TICKET_BARCODE_HAD_SCANED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 must have manifest UID or Bol UID. 的當地語系化字串。
        /// </summary>
        public static string TICKET_GENERATETICKET_PARAMETER_NULL {
            get {
                return ResourceManager.GetString("TICKET_GENERATETICKET_PARAMETER_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find attachment folders. 的當地語系化字串。
        /// </summary>
        public static string TICKET_GETATTACHMENTLIST_ERROR {
            get {
                return ResourceManager.GetString("TICKET_GETATTACHMENTLIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 lost  OriginalSlotUID . 的當地語系化字串。
        /// </summary>
        public static string TICKET_LOST_ORIGINALSLOTUID {
            get {
                return ResourceManager.GetString("TICKET_LOST_ORIGINALSLOTUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find package. 的當地語系化字串。
        /// </summary>
        public static string TICKET_LOST_PACKAGE {
            get {
                return ResourceManager.GetString("TICKET_LOST_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 lost TargetPackage or OriginalPackage 的當地語系化字串。
        /// </summary>
        public static string TICKET_LOST_PACKAGE_INFO {
            get {
                return ResourceManager.GetString("TICKET_LOST_PACKAGE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 lost TargetSlotUID or OriginalSlotUID. 的當地語系化字串。
        /// </summary>
        public static string TICKET_LOST_SLOT_INFO {
            get {
                return ResourceManager.GetString("TICKET_LOST_SLOT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 lost TargetPackage. 的當地語系化字串。
        /// </summary>
        public static string TICKET_LOST_TARGETPACKAGE {
            get {
                return ResourceManager.GetString("TICKET_LOST_TARGETPACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 lost TargetSlotUID. 的當地語系化字串。
        /// </summary>
        public static string TICKET_LOST_TARGETSLOTUID {
            get {
                return ResourceManager.GetString("TICKET_LOST_TARGETSLOTUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not find workorder payload data. 的當地語系化字串。
        /// </summary>
        public static string TICKET_LOST_WORKORDER_PAYLOAD_DATA {
            get {
                return ResourceManager.GetString("TICKET_LOST_WORKORDER_PAYLOAD_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Can&apos;t be same as To Slot 的當地語系化字串。
        /// </summary>
        public static string TICKET_MOBILE_CHANGESLOT_FROMSLOT_CANNOT_SAME {
            get {
                return ResourceManager.GetString("TICKET_MOBILE_CHANGESLOT_FROMSLOT_CANNOT_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find ticketinfo. 的當地語系化字串。
        /// </summary>
        public static string TICKET_MOBILE_CHANGESLOT_NOTFINDTICKETINFO {
            get {
                return ResourceManager.GetString("TICKET_MOBILE_CHANGESLOT_NOTFINDTICKETINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Slot#{0} invalid. 的當地語系化字串。
        /// </summary>
        public static string TICKET_MOBILE_CHANGESLOT_SLOT_INVALID {
            get {
                return ResourceManager.GetString("TICKET_MOBILE_CHANGESLOT_SLOT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ticket must outbound. 的當地語系化字串。
        /// </summary>
        public static string TICKET_MOBILE_CHANGESLOT_TICKETMUSTOUTBOUND {
            get {
                return ResourceManager.GetString("TICKET_MOBILE_CHANGESLOT_TICKETMUSTOUTBOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ticket info status must before complete. 的當地語系化字串。
        /// </summary>
        public static string TICKET_MOBILE_CHANGESLOT_TICKETSTATUSINCORRECT {
            get {
                return ResourceManager.GetString("TICKET_MOBILE_CHANGESLOT_TICKETSTATUSINCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ticket type is not move. 的當地語系化字串。
        /// </summary>
        public static string TICKET_MOBILE_CHANGESLOT_TICKETTYPEINCORRECT {
            get {
                return ResourceManager.GetString("TICKET_MOBILE_CHANGESLOT_TICKETTYPEINCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 don&apos;t cross warehouse in ticket 的當地語系化字串。
        /// </summary>
        public static string TICKET_MOBILE_CHANGESLOT_TICKETWAREHOUSEINCORRECT {
            get {
                return ResourceManager.GetString("TICKET_MOBILE_CHANGESLOT_TICKETWAREHOUSEINCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 insufficient onhand , can&apos;t allocated 的當地語系化字串。
        /// </summary>
        public static string TICKET_MOBILE_CHANGESLOT_UNALLOWED_NEGATIVE {
            get {
                return ResourceManager.GetString("TICKET_MOBILE_CHANGESLOT_UNALLOWED_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This ticket type unallowed use change from function 的當地語系化字串。
        /// </summary>
        public static string TICKET_MOBILE_CHANGESLOT_UNALLOWED_USE {
            get {
                return ResourceManager.GetString("TICKET_MOBILE_CHANGESLOT_UNALLOWED_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Can&apos;t use chang from function 的當地語系化字串。
        /// </summary>
        public static string TICKET_MOBILE_CHANGESLOT_UNALLOWED_USE_CHANGEFROM {
            get {
                return ResourceManager.GetString("TICKET_MOBILE_CHANGESLOT_UNALLOWED_USE_CHANGEFROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not support undo action 的當地語系化字串。
        /// </summary>
        public static string TICKET_MOVE_NOTSUPPORT {
            get {
                return ResourceManager.GetString("TICKET_MOVE_NOTSUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Move seqment incorrect,please offposition first 的當地語系化字串。
        /// </summary>
        public static string TICKET_MOVE_SEQMENT_INCORRECT {
            get {
                return ResourceManager.GetString("TICKET_MOVE_SEQMENT_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ticket item is future allocated data, can&apos;t move 的當地語系化字串。
        /// </summary>
        public static string TICKET_MOVETICKET_HAS_FUTURE_ALLOCATED {
            get {
                return ResourceManager.GetString("TICKET_MOVETICKET_HAS_FUTURE_ALLOCATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find inventory data. 的當地語系化字串。
        /// </summary>
        public static string TICKET_NOT_FIND_INVENTORY {
            get {
                return ResourceManager.GetString("TICKET_NOT_FIND_INVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find payload data. 的當地語系化字串。
        /// </summary>
        public static string TICKET_NOT_FIND_PAYLOAD {
            get {
                return ResourceManager.GetString("TICKET_NOT_FIND_PAYLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find ticket info data. 的當地語系化字串。
        /// </summary>
        public static string TICKET_NOT_FIND_TICKETINFO {
            get {
                return ResourceManager.GetString("TICKET_NOT_FIND_TICKETINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Same tickets in following BulkPick {0} 的當地語系化字串。
        /// </summary>
        public static string TICKET_TICKET_IN_BULKPICK {
            get {
                return ResourceManager.GetString("TICKET_TICKET_IN_BULKPICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 undefined command. 的當地語系化字串。
        /// </summary>
        public static string TICKET_UNDEFINED_COMMAND {
            get {
                return ResourceManager.GetString("TICKET_UNDEFINED_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find receiving ticket 的當地語系化字串。
        /// </summary>
        public static string TICKET_UPLOADBYPOD_NOT_FIND_DATA {
            get {
                return ResourceManager.GetString("TICKET_UPLOADBYPOD_NOT_FIND_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to add vendor. 的當地語系化字串。
        /// </summary>
        public static string VENDOR_ADD_VENDOR_FAIL {
            get {
                return ResourceManager.GetString("VENDOR_ADD_VENDOR_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;Company&quot; can&apos;t be empty. 的當地語系化字串。
        /// </summary>
        public static string VENDOR_COMPANY_EMPTY {
            get {
                return ResourceManager.GetString("VENDOR_COMPANY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to delete vendor. 的當地語系化字串。
        /// </summary>
        public static string VENDOR_DELETE_VENDOR_FAIL {
            get {
                return ResourceManager.GetString("VENDOR_DELETE_VENDOR_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;Vendor ID&quot; can&apos;t be empty. 的當地語系化字串。
        /// </summary>
        public static string VENDOR_ID_EMPTY {
            get {
                return ResourceManager.GetString("VENDOR_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to update vendor. 的當地語系化字串。
        /// </summary>
        public static string VENDOR_UPDATE_VENDOR_FAIL {
            get {
                return ResourceManager.GetString("VENDOR_UPDATE_VENDOR_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 can&apos;t move different warehouse at same time 的當地語系化字串。
        /// </summary>
        public static string WAREHOSUE_MOVE_PAYLAOD_MULTIWAREHOUSE_REQUEST {
            get {
                return ResourceManager.GetString("WAREHOSUE_MOVE_PAYLAOD_MULTIWAREHOUSE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to add area. 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_ADD_AREA_FAIL {
            get {
                return ResourceManager.GetString("WAREHOUSE_ADD_AREA_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to add bin. 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_ADD_BIN_FAIL {
            get {
                return ResourceManager.GetString("WAREHOUSE_ADD_BIN_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to add home location 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_ADD_HOMEADDR_FAILURE {
            get {
                return ResourceManager.GetString("WAREHOUSE_ADD_HOMEADDR_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to add slot. 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_ADD_SLOT_FAIL {
            get {
                return ResourceManager.GetString("WAREHOUSE_ADD_SLOT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to add warehouse. 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_ADD_WAREHOUSE_FAIL {
            get {
                return ResourceManager.GetString("WAREHOUSE_ADD_WAREHOUSE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not find Slot UID {0} 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_CHECK_SLOT_NOT_EXIST {
            get {
                return ResourceManager.GetString("WAREHOUSE_CHECK_SLOT_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Slot status incorrect 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_CHECK_SLOT_STATAUS {
            get {
                return ResourceManager.GetString("WAREHOUSE_CHECK_SLOT_STATAUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to delete area. 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_DELETE_AREA_FAIL {
            get {
                return ResourceManager.GetString("WAREHOUSE_DELETE_AREA_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to delete bin. 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_DELETE_BIN_FAIL {
            get {
                return ResourceManager.GetString("WAREHOUSE_DELETE_BIN_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to delete home location 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_DELETE_HOMEADDR_FAILURE {
            get {
                return ResourceManager.GetString("WAREHOUSE_DELETE_HOMEADDR_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to delete slot. 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_DELETE_SLOT_FAIL {
            get {
                return ResourceManager.GetString("WAREHOUSE_DELETE_SLOT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to delete warehouse. 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_DELETE_WAREHOUSE_FAIL {
            get {
                return ResourceManager.GetString("WAREHOUSE_DELETE_WAREHOUSE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Can&apos;t change pkg 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_MODIFIED_ONHAND_CANNOTCHANGEPKG {
            get {
                return ResourceManager.GetString("WAREHOUSE_MODIFIED_ONHAND_CANNOTCHANGEPKG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The data include processing item, plesae finish scan ticket 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_MODIFIED_ONHAND_PAYLOAD_STATUS_ILLEGAL {
            get {
                return ResourceManager.GetString("WAREHOUSE_MODIFIED_ONHAND_PAYLOAD_STATUS_ILLEGAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 payload type  must onhand  的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_MODIFIED_ONHAND_PAYLOAD_TYPE_ILLEGAL {
            get {
                return ResourceManager.GetString("WAREHOUSE_MODIFIED_ONHAND_PAYLOAD_TYPE_ILLEGAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pkg not match item 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_MODIFIED_ONHAND_PKGNOTMATCH {
            get {
                return ResourceManager.GetString("WAREHOUSE_MODIFIED_ONHAND_PKGNOTMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find warehouse  的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_NOT_FIND {
            get {
                return ResourceManager.GetString("WAREHOUSE_NOT_FIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 not find loading zone. 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_NOT_FIND_LOADING_ZONE {
            get {
                return ResourceManager.GetString("WAREHOUSE_NOT_FIND_LOADING_ZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to update area. 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_UPDATE_AREA_FAIL {
            get {
                return ResourceManager.GetString("WAREHOUSE_UPDATE_AREA_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to update bin. 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_UPDATE_BIN_FAIL {
            get {
                return ResourceManager.GetString("WAREHOUSE_UPDATE_BIN_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to update slot. 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_UPDATE_SLOT_FAIL {
            get {
                return ResourceManager.GetString("WAREHOUSE_UPDATE_SLOT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to update warehouse. 的當地語系化字串。
        /// </summary>
        public static string WAREHOUSE_UPDATE_WAREHOUSE_FAIL {
            get {
                return ResourceManager.GetString("WAREHOUSE_UPDATE_WAREHOUSE_FAIL", resourceCulture);
            }
        }
    }
}
